# Generated by Django 5.1 on 2025-01-01 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0011_exam_subject"),
        ("staffs", "0004_alter_staff_pincode"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="known_subjects",
            field=models.ManyToManyField(blank=True, to="corecode.subject"),
        ),
    ]
