# Generated by Django 5.1 on 2024-12-10 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0006_remove_due_extended"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="Bill_No",
            field=models.CharField(default=None, max_length=245, unique=True),
        ),
    ]
