# Generated by Django 5.1 on 2024-12-12 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_alter_receipt_bill_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="receipt",
            name="Bill_No",
            field=models.CharField(default=None, max_length=245),
        ),
    ]
