# Generated by Django 5.1 on 2024-12-11 09:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0009_alter_schemes_options"),
        ("staffs", "0004_alter_staff_pincode"),
        ("students", "0008_student_alt_number_alter_exammodel_contected_mode_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="scheme",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="corecode.schemes",
            ),
        ),
        migrations.AddField(
            model_name="student",
            name="sse",
            field=models.ForeignKey(
                default=None,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="staffs.staff",
            ),
        ),
    ]
