# Generated by Django 5.1 on 2024-12-12 12:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0009_student_scheme_student_sse"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="student",
            name="sse",
        ),
    ]
