# Generated by Django 5.1 on 2024-12-31 18:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0010_remove_student_sse"),
    ]

    operations = [
        migrations.CreateModel(
            name="BreakDetails",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("break_start", models.DateField()),
                ("break_end", models.DateField()),
                ("reason", models.TextField(blank=True)),
                ("followup", models.JSONField(blank=True, default=list)),
                ("is_joined", models.BooleanField(default=False)),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="students.student",
                    ),
                ),
            ],
        ),
    ]
