# Generated by Django 5.1 on 2024-12-09 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0006_alter_exam_exam_duration_alter_subject_contents_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AccountHeading",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=260, unique=True)),
            ],
            options={
                "ordering": ["name"],
            },
        ),
    ]
