# Generated by Django 5.1 on 2024-12-11 09:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0008_schemes"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schemes",
            options={"ordering": ["scheme_status", "name"]},
        ),
    ]
