# Generated by Django 5.1 on 2024-12-31 05:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0010_exam_max_practical_marks_exam_max_theory_marks"),
    ]

    operations = [
        migrations.AddField(
            model_name="exam",
            name="subject",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="corecode.subject",
            ),
        ),
    ]
