# Generated by Django 5.1 on 2025-01-29 10:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("corecode", "0011_exam_subject"),
    ]

    operations = [
        migrations.CreateModel(
            name="Inventory",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("order_id", models.CharField(max_length=50, unique=True)),
                ("order_date", models.DateTimeField(auto_now_add=True)),
                ("items", models.JSONField(default=dict)),
                (
                    "content_type",
                    models.ForeignKey(
                        limit_choices_to={"models__in": ["book", "schemes"]},
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                    ),
                ),
            ],
        ),
    ]
