# Generated by Django 5.1 on 2025-01-29 17:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        ("corecode", "0012_inventory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="content_type",
            field=models.ForeignKey(
                limit_choices_to={"model__in": ["book", "schemes"]},
                on_delete=django.db.models.deletion.CASCADE,
                to="contenttypes.contenttype",
            ),
        ),
        migrations.AlterField(
            model_name="inventory",
            name="order_date",
            field=models.DateField(auto_now_add=True),
        ),
    ]
