# Generated by Django 5.1 on 2025-01-29 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0013_alter_inventory_content_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventory",
            name="order_date",
            field=models.DateField(),
        ),
    ]
