# Generated by Django 5.1 on 2024-12-26 12:33

from django.db import migrations

from ..models import DailyAccountData

def create_initial(apps, schema_editor):
    
    if not DailyAccountData.objects.exists():
        DailyAccountData.objects.create(opening_balance=0)

class Migration(migrations.Migration):

    dependencies = [
        ("revenue", "auto_opening_balance"),
    ]

    operations = [migrations.RunPython(create_initial)]
