# Generated by Django 5.1 on 2024-12-09 13:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("corecode", "0007_accountheading"),
        ("revenue", "0004_gst_gst_number"),
    ]

    operations = [
        migrations.CreateModel(
            name="Accounts",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Date", models.DateField(auto_now_add=True)),
                (
                    "Type",
                    models.CharField(
                        choices=[("Credit", "Credit"), ("Debit", "Debit")],
                        max_length=10,
                    ),
                ),
                ("Description", models.TextField()),
                ("Amount", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "Heading",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.DO_NOTHING,
                        to="corecode.accountheading",
                    ),
                ),
            ],
        ),
    ]
