# Generated by Django 5.1 on 2024-12-09 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("revenue", "0005_accounts"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="Date",
            field=models.DateField(),
        ),
    ]
