# Generated by Django 5.1 on 2024-12-10 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("revenue", "0006_alter_accounts_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accounts",
            name="Type",
            field=models.CharField(
                choices=[("Credit", "Credit"), ("Debit", "Debit")],
                default="Debit",
                max_length=10,
            ),
        ),
    ]
