# Generated by Django 5.1 on 2024-12-10 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("revenue", "0007_alter_accounts_type"),
    ]

    operations = [
        migrations.CreateModel(
            name="DailyAccountData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                (
                    "opening_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
                ("day_income", models.DecimalField(decimal_places=2, max_digits=10)),
                ("day_expence", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "closing_balance",
                    models.DecimalField(decimal_places=2, max_digits=10),
                ),
            ],
        ),
    ]
