# Generated by Django 4.2.14 on 2024-08-17 12:58

from django.db import migrations
from ..models import DailyAccountData

def create(apps, schema_editor):
    DailyAccountData.objects.create(opening_balance=0)

class Migration(migrations.Migration):

    dependencies = [
        ("revenue", "0009_remove_dailyaccountdata_closing_balance_and_more"),
    ]

    operations = [migrations.RunPython(create)]