# Generated by Django 5.1 on 2024-12-07 11:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("enquiry", "0013_alter_enquiry_counsellor"),
    ]

    operations = [
        migrations.RenameField(
            model_name="enquiry",
            old_name="alternate_mobile_number",
            new_name="alt_number",
        ),
        migrations.AlterField(
            model_name="enquiry",
            name="mobile_number",
            field=models.CharField(
                default="",
                max_length=13,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Entered mobile number isn't in a right format!",
                        regex="^[0-9]{10,15}$",
                    )
                ],
                verbose_name="Mobile Number",
            ),
        ),
    ]
